Renamed the core installation script

diff --git a/scripts/install_core b/scripts/install_core
--- a/scripts/install_core
+++ b/scripts/install_core
@@ -4,7 +4,7 @@
 #
 # prerequisites: Homebrew(Mac), Linuxbrew(Linux) is installed.
 #
-# Usage: curl -fsSL https://raw.githubusercontent.com/tbetbetbe/homebrew-grpc/master/scripts/install_grpc.sh | bash -
+# Usage: curl -fsSL https://raw.githubusercontent.com/tbetbetbe/homebrew-grpc/master/scripts/install_core | bash -
 
 __grpc_check_for_brew() {
     which 'brew' >> /dev/null || {
@@ -61,9 +61,22 @@ __grpc_install_with_brew() {
     __grpc_brew_install --HEAD grpc
 }
 
-main() {
-    __grpc_check_for_brew || exit 1;
-    __grpc_install_with_brew;
+__grpc_install_ruby() {
+    which 'ruby' >> /dev/null || {
+        echo "Could not detect ruby; please install it or add to the PATH and try again";
+        return 1;
+    }
+    gem install grpc -- --with-grpc-dir=$HOME/.linuxbrew
 }
 
-main
+main() {
+    echo "Args were: $@";
+    __grpc_check_for_brew || exit 1;
+    __grpc_install_with_brew;
+    if [[ "$@" =~ 'ruby' ]]; then
+       echo "ruby required! ";
+       __grpc_install_ruby;
+    fi
+}
+
+main "$@"
